"""
Contains the so-called coupler... which is really just a glorified job queue
for the main event loop to pull from to display current state of board and hero.
"""

import copy

__author__ = 'jessebostic'


class Coupler:
    """Class that handles a job queue for communication from model to view"""

    def __init__(self):
        """Creates the queue"""

        self.jobs = []

    def add_job(self, job):
        """Jobs are just dictionaries of strings to object refs.

        :param job: job to queue up
        :return None
        """

        self.jobs.append(job)

    def get_a_job(self):
        """Allows view to sequentially pull new events generated by model.

        :return next job in the queue
        """

        job = None
        if len(self.jobs) > 0:
            job = self.jobs.pop(0)
        return job

