import copy
from model.protag import Hero

__author__ = 'jessebostic'


class Coupler:
    """Class that handles a job queue for communication from model to view"""

    def __init__(self):
        self.jobs = []

    def add_job(self, job):
        """Jobs are just dictionaries of strings to object refs"""

        self.jobs.append(job)

    def ________________get_jobs(self):
        """Probably not useful"""

        jobs = copy.deepcopy(self.jobs)
        self.jobs = []
        return jobs

    def get_a_job(self):
        """Allows view to sequentially pull new events generated by model"""

        job = None
        if len(self.jobs) > 0:
            job = self.jobs.pop(0)
        return job

